### ISSUE TITLE
Site problems admin panel

### ISSUE THREAD

**Issue by AndrewCraft-Server** [IDzUp/pH2Date#2]
Website works fine so far everything works other then when i go to localhost/admin/ it is just a blank white page no error?
![image](https://user-images.githubusercontent.com/10123853/49903662-92856800-fe2d-11e8-94f8-212616b11d38.png)

**Comment by pH-7** [comment]
For your information, it has been fixed in #3, patch https://github.com/IDzUp/pH2Date/commit/1a4c61cc83400c9405984add4436ae5c26e87275

Hope it helps! Good luck!
