### ISSUE TITLE
admin page issue!

### ISSUE THREAD

**Issue by solamidemoses** [IDzUp/pH2Date#3]
After changing production to development in the root folder... I got this error message when trying to access the admin url
![error](https://user-images.githubusercontent.com/31577884/54861084-7b3dfc80-4cf1-11e9-80ac-f2dd69063fd4.JPG)

**Comment by pH-7** [comment]
Thanks for these details. Fixed in patch https://github.com/IDzUp/pH2Date/commit/1a4c61cc83400c9405984add4436ae5c26e87275

And updated its version in https://github.com/IDzUp/pH2Date/commit/ffa4539222d194332171b918dfa40b897e33eab8
