### ISSUE TITLE
Internal server error [HTTP/1.1 500 Internal Server Error 1900ms]

### ISSUE THREAD

**Issue by stephen-ask** [IDzUp/pH2Date#6]
Hi,
I have a internal server error issue after installing initial setup on subfolder name called beta

These are my htaccess code 
 RewriteEngine on
     RewriteBase /beta/

    # Prevent CI index.php
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule .* /beta/index.php/$0 [PT,L]

    # Prevent user access to the CI system folder.
    RewriteCond %{REQUEST_URI} ^system.*
    RewriteRule ^(.*)$ /beta/index.php?/$1 [L]

    # Prevent user access to the CI application folder
    RewriteCond %{REQUEST_URI} ^application.*
    RewriteRule ^(.*)$ /beta/index.php?/$1 [L]

Thanks,

**Comment by pH-7** [comment]
Hey @stephen-ask Can you let me know what Apache version you are using?

**Comment by stephen-ask** [comment]
Server version: Apache/2.4.35 (Win64)

**Comment by ph7ali** [comment]
Same error wash shown in local server with xampp. When i changed it as development mode so it shows following error:
Frtal error: Uncaight Error: Undefined constant "VIEWPATH" in c:/xampp ..........ph2date/system/core/common.php line 659.
Exception error thrown  . Xampp ..../ ph2date/system/core/Exceptions.php .


In general environment   it shows  Error 500.

**Comment by ph7ali** [comment]
Same error wash shown in local server with xampp. When i changed it as development mode so it shows following error:
Fatal error: Uncaught Error: Undefined constant "VIEWPATH" in c:/xampp ..../ph2date /system /core/Exceptions.php  line 195.....Stack trace: #0 C://xampp....ph2date/system/core/common.php line 659.
Exception error thrown  . Xampp ..../ ph2date/system/core/Exceptions.php .

In general environment   it shows  Error 500..
Let me know if you find solutions.  But you can check out another ph7 cms solution. 
On my same setup the ph7cms 16.2.2 can run.  Thank you

**Comment by pH-7** [comment]
Hi again @stephen-ask 

I had a look to your problem. It seems you modified `system/core/common.php` (or you got a modified version of it).
pH2Date doesn't have `VIEWPATH` constant.  Please make sure you use the latest version of the file here https://github.com/IDzUp/pH2Date/blob/master/system/core/Common.php, or fix the undefined `VIEWPATH` constant from your modified one.

Hope it helps! 😊
