### ISSUE TITLE
 ph2date.com 

### ISSUE THREAD

**Issue by digitella** [IDzUp/pH2Date#7]
ph2date.com seems to be broken

**Comment by pH-7** [comment]
Hi @digitella! Thanks for reporting this! Yes, I'm aware of it, and that's fine 🙂 https://github.com/IDzUp/pH2Date/commit/3534e4c73503f24a2774e8780e8bd68e233be900. However, the script will continue to be available on this repository. By now, please refer to this URL only https://github.com/IDzUp/pH2Date/issues/7

Have a great day ahead ☀️
