### ISSUE TITLE
dealing with requested class: session

### ISSUE THREAD

**Issue by SeremTitus** [IDzUp/pH2Date#9]
i keep getting this error :Unable to load the requested class: session

**Comment by pH-7** [comment]
Hi @seremempire 🙂

Interesting one. Have you changed anything in the code? Are you using the `master`/`main` branch?

**Comment by seremempire** [comment]
> Hi @seremempire slightly_smiling_face
> 
> Interesting one. Have you changed anything in the code? Are you using the `master`/`main` branch?

**Comment by SeremTitus** [comment]
@pH-7, At the time of issue report I was still in master

**Comment by pH-7** [comment]
That’s interesting… That you for reporting this with me.
Once I have the time, I will test it on my local server.
